// Generated by Dagger (https://dagger.dev).
package com.woodnoisu.reader.di;

import com.woodnoisu.ktReader.network.HtmlService;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class NetworkModule_ProvideHtmlServiceFactory implements Factory<HtmlService> {
  @Override
  public HtmlService get() {
    return provideHtmlService();
  }

  public static NetworkModule_ProvideHtmlServiceFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static HtmlService provideHtmlService() {
    return Preconditions.checkNotNullFromProvides(NetworkModule.INSTANCE.provideHtmlService());
  }

  private static final class InstanceHolder {
    private static final NetworkModule_ProvideHtmlServiceFactory INSTANCE = new NetworkModule_ProvideHtmlServiceFactory();
  }
}
