// Generated by Dagger (https://dagger.dev).
package com.woodnoisu.reader.di;

import com.squareup.moshi.Moshi;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PersistenceModule_ProvideMoshiFactory implements Factory<Moshi> {
  @Override
  public Moshi get() {
    return provideMoshi();
  }

  public static PersistenceModule_ProvideMoshiFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static Moshi provideMoshi() {
    return Preconditions.checkNotNullFromProvides(PersistenceModule.INSTANCE.provideMoshi());
  }

  private static final class InstanceHolder {
    private static final PersistenceModule_ProvideMoshiFactory INSTANCE = new PersistenceModule_ProvideMoshiFactory();
  }
}
