// Generated by Dagger (https://dagger.dev).
package com.woodnoisu.reader.di;

import android.app.Application;
import com.woodnoisu.ktReader.persistence.AppDataBase;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class PersistenceModule_ProvideAppDatabaseFactory implements Factory<AppDataBase> {
  private final Provider<Application> applicationProvider;

  public PersistenceModule_ProvideAppDatabaseFactory(Provider<Application> applicationProvider) {
    this.applicationProvider = applicationProvider;
  }

  @Override
  public AppDataBase get() {
    return provideAppDatabase(applicationProvider.get());
  }

  public static PersistenceModule_ProvideAppDatabaseFactory create(
      Provider<Application> applicationProvider) {
    return new PersistenceModule_ProvideAppDatabaseFactory(applicationProvider);
  }

  public static AppDataBase provideAppDatabase(Application application) {
    return Preconditions.checkNotNullFromProvides(PersistenceModule.INSTANCE.provideAppDatabase(application));
  }
}
